==========================================Table======================

1. USER_INVOICE

 CREATE TABLE "USER_INVOICE" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(10), 
	"PASSWORD" VARCHAR2(10), 
	"CREATED_ON" DATE
   ) ;
   
2.SUPPLIER_DETAILS

  CREATE TABLE "SUPPLIER_DETAILS" 
   (	"SUPPLIER_NAME" VARCHAR2(100), 
	"CONTACT_PERSON" VARCHAR2(100), 
	"CONTACT_NUMBER" NUMBER, 
	"SUPPLIER_ADDRESS" VARCHAR2(255), 
	"EMAIL" VARCHAR2(100), 
	"GSTIN" VARCHAR2(100), 
	"PAN" VARCHAR2(100), 
	"CITY" VARCHAR2(100), 
	"PIN_CODE" VARCHAR2(100), 
	"ATTRIBUTE5" VARCHAR2(100), 
	"LINK_COLUMN" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"UPDATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	"INVOICE_NUMBER" VARCHAR2(100)
   ) ;
   
   
3.  BUYER_DETAILS

  CREATE TABLE "BUYER_DETAILS" 
   (	"BUYER_NAME" VARCHAR2(100), 
	"CONSIGNEE_NAME" VARCHAR2(100), 
	"CONTACT_NUMBER" VARCHAR2(15), 
	"ADDRESS" VARCHAR2(255), 
	"EMAIL" VARCHAR2(100), 
	"GSTIN" VARCHAR2(100), 
	"CITY" VARCHAR2(100), 
	"GST_TREATEMENT_TYPE" VARCHAR2(100), 
	"STATE" VARCHAR2(100), 
	"PIN_CODE" VARCHAR2(100), 
	"LINK_COLUMN" NUMBER NOT NULL ENABLE, 
	"BUYER_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"UPDATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE
   ) ;

4. BANK_DETAILS

  CREATE TABLE "BANK_DETAILS" 
   (	"BANK_NAME" VARCHAR2(100), 
	"ACCOUNT_NUMBER" VARCHAR2(50), 
	"IFSC_CODE" VARCHAR2(20), 
	"BRANCH_NAME" VARCHAR2(100), 
	"ACCOUNT_HOLDER" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"ATTRIBUTE2" VARCHAR2(100), 
	"ATTRIBUTE3" VARCHAR2(100), 
	"ATTRIBUTE4" VARCHAR2(100), 
	"ATTRIBUTE5" VARCHAR2(100), 
	"LINK_COLUMN" NUMBER NOT NULL ENABLE, 
	"BANK_ID" NUMBER, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50), 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50)
   ) ;

5. OTHER_DETAILS

  CREATE TABLE "OTHER_DETAILS" 
   (	"GST_NUMBER" VARCHAR2(20), 
	"INVOICE_NUMBER" VARCHAR2(50), 
	"INVOICE_DATE" DATE, 
	"PAYMENT_TERMS" VARCHAR2(100), 
	"REMARKS" VARCHAR2(255), 
	"CHALAN_NUMBER" VARCHAR2(100), 
	"CURRIER_CHARGE" VARCHAR2(100), 
	"PACKING_CHARGE" VARCHAR2(100), 
	"OTHER_CHARGE" VARCHAR2(100), 
	"ATTRIBUTE5" VARCHAR2(100), 
	"LINK_COLUMN" NUMBER NOT NULL ENABLE, 
	"DETAIL_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(50)
   ) ;

6. PRODUCT_DETAILS_HEADER

  CREATE TABLE "PRODUCT_DETAILS_HEADER" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100), 
	"PRODUCT_TYPE" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"LINK_COLUMN" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"UPDATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE
   ) ;

7. PRODUCT_DETAILS_LINE

  CREATE TABLE "PRODUCT_DETAILS_LINE" 
   (	"ITEM_NAME" VARCHAR2(100), 
	"QUANTITY" NUMBER, 
	"UNIT_PRICE" NUMBER(10,2), 
	"TOTAL_PRICE" NUMBER(10,2), 
	"CREATION_DATE" DATE, 
	"PRODUCT_ID" NUMBER, 
	"SL_NO" NUMBER, 
	"ATTRIBUTE4" VARCHAR2(100), 
	"ATTRIBUTE5" VARCHAR2(100), 
	"LINK_COLUMN" NUMBER, 
	"CREATED_BY" VARCHAR2(50), 
	"UPDATED_BY" VARCHAR2(50), 
	"CREATED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"GST_TAX_AMOUNT" NUMBER, 
	"GST_TAX_TYPE" VARCHAR2(100)
   ) ;
   
=========================TRIGGER======================================   

  CREATE OR REPLACE EDITIONABLE TRIGGER "TOTAL_PERCENTEGE_TRIG" 
BEFORE INSERT OR UPDATE ON PRODUCT_DETAILS_LINE
FOR EACH ROW
BEGIN
    :NEW.gst_tax_amount := :NEW.QUANTITY * :NEW.UNIT_PRICE * :NEW.gst_tax_type/100;
END;
/
ALTER TRIGGER "TOTAL_PERCENTEGE_TRIG" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TOTAL_PRICE_TRIG" 
BEFORE INSERT OR UPDATE ON PRODUCT_DETAILS_LINE
FOR EACH ROW
BEGIN
    :NEW.TOTAL_PRICE := :NEW.QUANTITY * :NEW.UNIT_PRICE;
END;
/
ALTER TRIGGER "TOTAL_PRICE_TRIG" ENABLE;


=========================FUNCTION=========================================

create or replace FUNCTION  "AUTH_INV"  
(p_username in varchar2, p_password in varchar2) 
return boolean 
as 
    user_check varchar2(1); 
begin 
    select 'x' 
    into user_check 
    from USER_INVOICE 

    where upper(USERNAME) = upper(p_username) and PASSWORD= p_password;
    --and APP_IDS=&APP_ID.;
   apex_util.set_authentication_result(0); 
    return true; 
exception when no_data_found then 
   apex_util.set_authentication_result(4); 
   return false; 
     
end AUTH_INV;
/




   